const KEY='kontur-finance-v1';
const nav=[['home','⌂','Главная'],['entry','↔','Ввод'],['plan','▣','План'],['analytics','▥','Аналитика'],['goals','◇','Цели'],['settings','⚙','Настройки']];
const defaults={settings:{incomeMain:85000,incomeSecond:15000,paydayMain:15,paydaySecond:29,goal:1000000},operations:[
 {id:'o1',date:'2026-06-03',type:'Расход',category:'Продукты',subcategory:'Супермаркет',amount:12800,account:'Основная карта',plannedFlag:'Плановая',comment:'',group:'Дом'},
 {id:'o2',date:'2026-06-06',type:'Расход',category:'Кафе',subcategory:'Кофе и обед',amount:4200,account:'Основная карта',plannedFlag:'Неплановая',comment:'',group:'Личное'},
 {id:'o3',date:'2026-06-10',type:'Расход',category:'Аренда',subcategory:'Квартира',amount:25000,account:'Основная карта',plannedFlag:'Плановая',comment:'',group:'Дом'},
 {id:'o4',date:'2026-06-12',type:'Расход',category:'ЖКХ',subcategory:'Счета',amount:9000,account:'Основная карта',plannedFlag:'Плановая',comment:'',group:'Дом'},
 {id:'o5',date:'2026-06-15',type:'Доход',category:'Зарплата',subcategory:'Основная часть',amount:85000,account:'Основная карта',plannedFlag:'Плановая',comment:'',group:'Доход'},
 {id:'o6',date:'2026-06-16',type:'Накопления',category:'Подушка безопасности',subcategory:'Взнос',amount:12500,account:'Накопительный счёт',plannedFlag:'Плановая',comment:'',group:'Цели'},
 {id:'o7',date:'2026-06-17',type:'Кредитка',category:'Кредитка',subcategory:'Платёж',amount:6500,account:'Кредитка',plannedFlag:'Плановая',comment:'',group:'Финансы'}],
 plans:[{id:'p1',date:'2026-06-19',type:'Расход',category:'Кафе',subcategory:'Кафе',title:'Поход в кафе',amount:2500,priority:'Желательно',status:'Запланировано',comment:''},{id:'p2',date:'2026-06-24',type:'Расход',category:'Медицина',subcategory:'Витамины',title:'Магний',amount:2500,priority:'Желательно',status:'Запланировано',comment:''},{id:'p3',date:'2026-06-29',type:'Доход',category:'Зарплата',subcategory:'Вторая часть',title:'Вторая часть зарплаты',amount:15000,priority:'Обязательно',status:'Запланировано',comment:''},{id:'p4',date:'2026-06-21',type:'Кредитка',category:'Кредитка',subcategory:'Платёж',title:'Доплатить по плану',amount:1500,priority:'Обязательно',status:'Запланировано',comment:''}],
 categories:[{name:'Аренда',controlType:'fixed',amount:25000},{name:'ЖКХ',controlType:'fixed',amount:9000},{name:'Продукты',controlType:'limit',amount:22000},{name:'Кафе',controlType:'limit',amount:6000},{name:'Доставка',controlType:'limit',amount:5000},{name:'Медицина',controlType:'none',amount:0},{name:'Кредитка',controlType:'plan',amount:8000},{name:'Подушка безопасности',controlType:'goal',amount:1000000}],goalSaved:650000};
let state=load(),active='home',filter='Все';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(n))+' ₽';
const el=(s)=>document.querySelector(s); const sum=(a,fn)=>a.reduce((x,v)=>x+fn(v),0);
function facts(type){return sum(state.operations.filter(o=>!type||o.type===type),o=>+o.amount)}
function activePlans(type){return sum(state.plans.filter(p=>p.status!=='Отменено'&&p.status!=='Выполнено'&&(!type||p.type===type)),p=>+p.amount)}
function totals(){const inc=facts('Доход'),exp=facts('Расход'),save=facts('Накопления'),credit=facts('Кредитка');return{inc,exp,save,credit,balance:inc-exp-save-credit,forecast:inc+activePlans('Доход')-exp-save-credit-activePlans('Расход')-activePlans('Накопления')-activePlans('Кредитка')}}
function renderNav(){for(const id of ['#mobileNav','#desktopNav'])el(id).innerHTML=nav.map(([k,icon,label])=>`<button class="nav-item ${k===active?'active':''}" data-nav="${k}"><b>${icon}</b><span>${label}</span></button>`).join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>{active=b.dataset.nav;render()})}
function render(){renderNav();({home:homeScreen,entry:entryScreen,plan:planScreen,analytics:analyticsScreen,goals:goalsScreen,settings:settingsScreen}[active])();window.scrollTo({top:0,behavior:'smooth'})}
function title(h,p){return `<div class="section-head"><h1>${h}</h1><p>${p||''}</p></div>`}
function homeScreen(){const t=totals(),plannedExp=activePlans('Расход')+activePlans('Кредитка')+activePlans('Накопления'),monthPlan=state.categories.filter(c=>['fixed','limit','plan'].includes(c.controlType)).reduce((a,c)=>a+c.amount,0),pct=Math.min(100,Math.round((t.exp+t.credit)/monthPlan*100)||0);el('#screen').innerHTML=`<div class="stack dashboard-grid">
<section class="hero"><div class="eyebrow">Доступно сейчас</div><div class="hero-value">${money(t.balance)}</div><div class="hero-line"></div><div class="hero-caption">На всех счетах после накоплений</div></section>
<section class="card paydays"><div class="payday"><div class="calendar-icon">▣</div><div><small>до аванса</small><strong>9</strong> <em>дней</em><span>29 июня</span></div></div><div class="payday"><div class="calendar-icon">▣</div><div><small>до зарплаты</small><strong>25</strong> <em>дней</em><span>15 июля</span></div></div><div class="forecast"><div><small class="eyebrow">Прогноз остатка<br>на конец месяца</small><div class="forecast-value">${money(t.forecast)}</div><p class="muted">После активных планов</p></div><svg class="sparkline" viewBox="0 0 240 75"><polyline points="3,60 35,46 67,51 99,30 131,36 163,20 195,25 237,10"/>${[[3,60],[35,46],[67,51],[99,30],[131,36],[163,20],[195,25],[237,10]].map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="3"/>`).join('')}</svg></div></section>
<section class="card"><div class="card-title">План месяца <span style="float:right;font-weight:400">Июнь 2026</span></div><div class="plan-overview"><div><span>План</span><strong>${money(monthPlan)}</strong></div><div><span>Факт</span><strong>${money(t.exp+t.credit)}</strong></div><div><span>Осталось</span><strong style="color:var(--gold)">${money(monthPlan-t.exp-t.credit)}</strong></div></div><div class="progress"><i style="width:${pct}%"></i></div><p class="muted">${pct}% от плана · активные планы ${money(plannedExp)}</p><div class="chart">${[18,25,31,38,49,57,69,78,88,98,110,121,132,140].map((h,i)=>`<div class="bar" style="height:${h/1.5}px;--fact:${Math.max(5,105-i*7)}px"></div>`).join('')}</div></section>
<section class="mini-grid"><div class="card metric"><div class="label">Подушка безопасности</div><div class="value">${Math.round(state.goalSaved/state.settings.goal*100)}%</div><div class="progress"><i style="width:${state.goalSaved/state.settings.goal*100}%"></i></div><p>${money(state.goalSaved)} из ${money(state.settings.goal)}</p></div><div class="card metric"><div class="label">Кредитная нагрузка</div><div class="value">${Math.round(t.credit/8000*100)}%</div><div class="progress"><i style="width:${Math.min(100,t.credit/80)}%"></i></div><p>${money(t.credit)} из 8 000 ₽</p></div><div class="card metric"><div class="label">Фин. рейтинг</div><div class="value gold">82<small>/100</small></div><p>Отлично</p></div></section>
<section class="card"><div class="card-title">Расходы за месяц <span style="float:right;font-size:16px">${money(t.exp)}</span></div><div class="donut-row"><div class="donut"><div class="donut-center">Всего<strong>${money(t.exp)}</strong></div></div><div class="legend">${expenseLegend()}</div></div></section>
<section class="card"><div class="card-title">Распределение зарплаты</div><p class="report">После основной зарплаты 15 числа сначала распределите обязательные платежи, плановые расходы, кредитку и накопления. 29 числа приходит малая часть дохода — ${money(state.settings.incomeSecond)}.</p><div class="insight">Следующий шаг: зарезервировать ${money(activePlans('Расход')+activePlans('Кредитка'))} на активные планы.</div></section></div>`}
function expenseLegend(){const cats={};state.operations.filter(o=>o.type==='Расход').forEach(o=>cats[o.category]=(cats[o.category]||0)+o.amount);return Object.entries(cats).sort((a,b)=>b[1]-a[1]).slice(0,6).map(([k,v],i)=>`<div class="legend-item"><i class="dot" style="opacity:${1-i*.1}"></i><span>${k}</span><b>${money(v)}</b></div>`).join('')}
function entryScreen(){el('#screen').innerHTML=`<div class="stack">${title('Операции','Факт, а не намерения')}<form id="opForm" class="card form-card"><div class="field"><label>Дата</label><input name="date" type="date" value="2026-06-20" required></div><div class="field"><label>Тип операции</label><select name="type">${['Расход','Доход','Накопления','Кредитка'].map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Категория</label><select name="category">${state.categories.map(c=>`<option>${c.name}</option>`)}</select></div><div class="field"><label>Подкатегория</label><input name="subcategory" placeholder="Например, супермаркет"></div><div class="field"><label>Сумма</label><input name="amount" type="number" min="1" placeholder="0" required></div><div class="field"><label>Счёт</label><select name="account">${['Основная карта','Кредитка','Наличные','Накопительный счёт'].map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Плановость</label><select name="plannedFlag"><option>Плановая</option><option>Неплановая</option></select></div><div class="field"><label>Группа / тег</label><input name="group" placeholder="Дом, личное…"></div><div class="field full"><label>Комментарий</label><textarea name="comment" rows="2"></textarea></div><button class="button gold full">Добавить операцию</button></form><div class="filter-row">${['Все','Расход','Доход','Накопления','Кредитка','Неплановая'].map(x=>`<button class="chip ${filter===x?'active':''}" data-filter="${x}">${x}</button>`).join('')}</div><div class="list">${operationList()}</div></div>`;el('#opForm').onsubmit=addOperation;document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;entryScreen()})}
function operationList(){let a=[...state.operations].reverse();if(filter!=='Все')a=a.filter(o=>filter==='Неплановая'?o.plannedFlag===filter:o.type===filter);return a.length?a.map(o=>`<div class="list-item"><div class="list-icon">${o.type==='Доход'?'＋':o.type==='Расход'?'−':'◇'}</div><div><strong>${o.subcategory||o.category}</strong><small>${o.category} · ${new Date(o.date+'T00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'})} · ${o.account}</small>${o.plannedFlag==='Неплановая'?'<span class="status warn">Неплановая</span>':''}</div><div class="amount ${o.type==='Доход'?'income':'expense'}">${o.type==='Доход'?'+':'−'}${money(o.amount)}</div></div>`).join(''):'<div class="empty">Нет операций по этому фильтру</div>'}
function addOperation(e){e.preventDefault();const f=new FormData(e.target),o=Object.fromEntries(f.entries());o.id='o'+Date.now();o.amount=+o.amount;o.createdAt=new Date().toISOString();state.operations.push(o);save();toast('Операция добавлена');entryScreen()}
function planScreen(){el('#screen').innerHTML=`<div class="stack">${title('План месяца','Лимиты, планы и цели считаются отдельно')}<div class="card"><div class="card-title">Контроль категорий</div><div class="stack">${state.categories.filter(c=>c.controlType!=='none'&&c.controlType!=='goal').map(categoryCard).join('')}</div></div><form id="planForm" class="card form-card"><div class="card-title full">Новая плановая операция</div><div class="field"><label>Дата</label><input name="date" type="date" value="2026-06-25" required></div><div class="field"><label>Тип</label><select name="type">${['Расход','Доход','Накопления','Кредитка'].map(x=>`<option>${x}</option>`)}</select></div><div class="field"><label>Категория</label><select name="category">${state.categories.map(c=>`<option>${c.name}</option>`)}</select></div><div class="field"><label>Название</label><input name="title" required></div><div class="field"><label>Сумма</label><input name="amount" type="number" min="1" required></div><div class="field"><label>Приоритет</label><select name="priority"><option>Обязательно</option><option>Желательно</option><option>Можно отложить</option></select></div><div class="field"><label>Статус</label><select name="status"><option>Запланировано</option><option>Выполнено</option><option>Отменено</option><option>Перенесено</option></select></div><button class="button gold">Добавить в план</button></form><div class="card"><div class="card-title">Активные планы</div><div class="list">${planList()}</div></div></div>`;el('#planForm').onsubmit=addPlan;document.querySelectorAll('[data-plan-status]').forEach(b=>b.onchange=()=>updatePlan(b.dataset.id,b.value))}
function categoryCard(c){const fact=sum(state.operations.filter(o=>o.category===c.name),o=>o.amount),plan=sum(state.plans.filter(p=>p.category===c.name&&p.status==='Запланировано'),p=>p.amount),total=fact+plan,pct=c.amount?Math.min(100,total/c.amount*100):0;let label={fixed:'Фиксированный платёж',limit:'Лимит',plan:'План'}[c.controlType],msg=c.controlType==='fixed'?(fact>=c.amount?'Оплачено':'Не оплачено'):c.controlType==='plan'?(fact<c.amount?`Нужно доплатить ${money(c.amount-fact)}`:'План выполнен'):(total>c.amount?'Требует разбора':'В пределах лимита');return `<div class="category-card"><div class="category-head"><div><strong>${c.name}</strong><div class="category-meta">${label}</div></div><span class="status ${total>c.amount&&c.controlType==='limit'?'warn':'good'}">${msg}</span></div><div class="category-values"><div>Факт<strong>${money(fact)}</strong></div><div>Активный план<strong>${money(plan)}</strong></div><div>Остаток<strong>${money(c.amount-total)}</strong></div></div><div class="progress"><i style="width:${pct}%"></i></div></div>`}
function planList(){return state.plans.map(p=>`<div class="list-item"><div class="list-icon">▣</div><div><strong>${p.title}</strong><small>${p.category} · ${new Date(p.date+'T00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'short'})}</small><span class="status ${p.status==='Отменено'?'warn':p.status==='Выполнено'?'good':''}">${p.status}</span></div><div><div class="amount">${money(p.amount)}</div><select data-plan-status data-id="${p.id}" aria-label="Статус"><option>${p.status}</option>${['Запланировано','Выполнено','Отменено','Перенесено'].filter(x=>x!==p.status).map(x=>`<option>${x}</option>`)}</select></div></div>`).join('')}
function addPlan(e){e.preventDefault();const p=Object.fromEntries(new FormData(e.target).entries());p.id='p'+Date.now();p.amount=+p.amount;p.createdAt=new Date().toISOString();p.subcategory='';p.comment='';state.plans.push(p);save();toast('План добавлен');planScreen()}
function updatePlan(id,status){const p=state.plans.find(x=>x.id===id);if(p){p.status=status;save();planScreen()}}
function analyticsScreen(){const t=totals(),unplanned=state.operations.filter(o=>o.type==='Расход'&&o.plannedFlag==='Неплановая'),over=state.categories.filter(c=>c.controlType==='limit'&&(sum(state.operations.filter(o=>o.category===c.name),o=>o.amount)+sum(state.plans.filter(p=>p.category===c.name&&p.status==='Запланировано'),p=>p.amount)>c.amount));el('#screen').innerHTML=`<div class="stack">${title('Аналитика','Июнь 2026')}<div class="wide-grid"><section class="card"><div class="card-title">Структура расходов</div><div class="donut-row"><div class="donut"><div class="donut-center">Факт<strong>${money(t.exp)}</strong></div></div><div class="legend">${expenseLegend()}</div></div></section><section class="card"><div class="card-title">Факт и активный план</div><div class="chart">${[38,55,28,74,45,68,90,82,105,121].map((h,i)=>`<div class="bar" style="height:${h}px;--fact:${Math.max(3,100-i*9)}px"></div>`).join('')}</div><p class="muted">Серые столбцы — план, тёмная линия — накопленный факт</p></section></div><section class="card"><div class="card-title">Что требует внимания</div><div class="stack">${over.length?over.map(c=>`<div class="insight"><strong>${c.name}</strong> — факт и активные планы выше лимита. Требует разбора, но не является критической ошибкой.</div>`).join(''):'<div class="insight">Категорий с превышением лимита нет.</div>'}${unplanned.length?`<div class="insight"><strong>Неплановые покупки: ${unplanned.length}</strong>. Повторяющиеся траты можно сделать плановыми или учесть в лимите.</div>`:''}</div></section><section class="card"><div class="card-title">Финансовый отчёт месяца</div><p class="report">Доход составил <strong>${money(t.inc)}</strong>, фактические расходы — <strong>${money(t.exp)}</strong>. Активный план расходов — <strong>${money(activePlans('Расход'))}</strong>, прогноз остатка — <strong>${money(t.forecast)}</strong>. На кредитку направлено ${money(t.credit)}, в подушку — ${money(t.save)}. ${over.length?'Основное внимание стоит уделить категориям: '+over.map(x=>x.name).join(', ')+'.':'Лимиты расходов соблюдаются.'}</p></section></div>`}
function goalsScreen(){const pct=Math.round(state.goalSaved/state.settings.goal*100);el('#screen').innerHTML=`<div class="stack">${title('Цели','Подушка безопасности')}<section class="card goal-hero"><div class="eyebrow">Накоплено сейчас</div><div class="hero-value" style="font-size:48px">${money(state.goalSaved)}</div><div class="progress"><i style="width:${pct}%"></i></div><div class="goal-numbers"><span>${pct}% цели</span><span>Осталось ${money(state.settings.goal-state.goalSaved)}</span></div></section><section class="card"><div class="card-title">Калькулятор темпа</div><div class="scenario-grid"><button class="scenario"><span>Комфортный</span><strong>15 000 ₽</strong><small>24 мес.</small></button><button class="scenario active"><span>Средний</span><strong>25 000 ₽</strong><small>14 мес.</small></button><button class="scenario"><span>Быстрый</span><strong>40 000 ₽</strong><small>9 мес.</small></button></div></section><section class="card"><div class="card-title">Планирование бюджета</div><div class="filter-row">${[100000,120000,150000].map((x,i)=>`<button class="chip ${i===0?'active':''}" data-income="${x}">${money(x)}</button>`).join('')}<button class="chip" data-income="custom">Свой вариант</button></div><div id="budgetScenario" style="margin-top:18px">${scenario(100000)}</div></section></div>`;document.querySelectorAll('[data-income]').forEach(b=>b.onclick=()=>{let v=b.dataset.income;if(v==='custom')v=prompt('Введите доход',120000);if(+v>0){document.querySelectorAll('[data-income]').forEach(x=>x.classList.remove('active'));b.classList.add('active');el('#budgetScenario').innerHTML=scenario(+v)}})}
function scenario(income){const required=34000,plans=activePlans('Расход')+8000,free=Math.max(0,income-required-plans),saving=Math.round(free*.55);return `<div class="plan-overview"><div><span>Обязательное</span><strong>${money(required)}</strong></div><div><span>Планы</span><strong>${money(plans)}</strong></div><div><span>Свободно</span><strong style="color:var(--gold)">${money(free)}</strong></div></div><div class="insight">Можно отложить около ${money(saving)}. При таком темпе подушка будет собрана за ${Math.ceil((state.settings.goal-state.goalSaved)/Math.max(1,saving))} мес.</div>`}
function settingsScreen(){el('#screen').innerHTML=`<div class="stack">${title('Настройки','Данные остаются на устройстве')}<section class="card"><div class="card-title">Доход по умолчанию</div><div class="setting-row"><span>Основная зарплата · ${state.settings.paydayMain} число</span><input id="incomeMain" type="number" value="${state.settings.incomeMain}"></div><div class="setting-row"><span>Вторая часть · ${state.settings.paydaySecond} число</span><input id="incomeSecond" type="number" value="${state.settings.incomeSecond}"></div><div class="setting-row"><span>Цель подушки</span><input id="goalAmount" type="number" value="${state.settings.goal}"></div><button id="saveSettings" class="button gold" style="margin-top:16px">Сохранить</button></section><section class="card"><div class="card-title">Данные</div><p class="muted">Экспортируйте резервную копию или перенесите данные на другое устройство.</p><div class="button-row"><button id="exportJson" class="button">Экспорт JSON</button><button id="exportCsv" class="button secondary">Экспорт CSV</button><label class="button secondary">Импорт JSON<input id="importJson" type="file" accept="application/json" hidden></label></div></section><section class="card"><div class="card-title">О приложении</div><p class="report">Контур работает без сервера и хранит данные в localStorage браузера. Лимит, план, фиксированный платёж и цель — разные сущности и рассчитываются независимо.</p><button id="resetData" class="button secondary">Вернуть демо-данные</button></section></div>`;el('#saveSettings').onclick=()=>{state.settings.incomeMain=+el('#incomeMain').value;state.settings.incomeSecond=+el('#incomeSecond').value;state.settings.goal=+el('#goalAmount').value;save();toast('Настройки сохранены')};el('#exportJson').onclick=()=>download('kontur-backup.json',JSON.stringify(state,null,2),'application/json');el('#exportCsv').onclick=exportCsv;el('#importJson').onchange=importJson;el('#resetData').onclick=()=>{if(confirm('Вернуть исходные демо-данные?')){state=structuredClone(defaults);save();render();toast('Демо-данные восстановлены')}}}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportCsv(){const h=['date','type','category','subcategory','amount','account','plannedFlag','comment','group'],q=v=>'"'+String(v??'').replaceAll('"','""')+'"';download('kontur-operations.csv','\ufeff'+h.join(';')+'\n'+state.operations.map(o=>h.map(k=>q(o[k])).join(';')).join('\n'),'text/csv')}
function importJson(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.operations||!d.plans)throw Error();state=d;save();render();toast('Данные импортированы')}catch{toast('Не удалось прочитать файл')}};r.readAsText(f)}
function toast(s){const t=el('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
render();
